### ISSUE TITLE
Change `swift-nio` Package dependency version (once `NIOAsyncSequenceProducer` has been released)

### ISSUE THREAD

**Issue by felixschlegel** [swift-server/swift-kafka-gsoc#23]
Our package makes use of `NIOAsyncSequenceProducer`. At the time of writing this issue, `NIOAsyncSequenceProducer` has not been included in an official [swit-nio](https://github.com/apple/swift-nio) release (version at the time of writing this: **2.41.1**).

Once a new [swit-nio](https://github.com/apple/swift-nio) version has been released, please change the `Package.swift` dependency as follows:

```diff
dependencies: [
-   .package(url: "https://github.com/apple/swift-nio.git", branch: "main"),
+   .package(url: "https://github.com/apple/swift-nio.git", from: <latest_version>),
    .package(url: "https://github.com/apple/swift-log.git", from: "1.0.0"),
],
```

**Comment by hassila** [comment]
https://github.com/apple/swift-nio/releases/tag/2.43.1 should have it now.

**Comment by felixschlegel** [comment]
Hey @hassila,

thank you for pointing that out! I have created a PR accordingly
