### ISSUE TITLE
Map `librdkafka`'s error types to Swift

### ISSUE THREAD

**Issue by felixschlegel** [swift-server/swift-kafka-gsoc#4]
* create an error type called `KafkaError` that contains all possible error names + their `code` and `description`
* update all existing `KafkaError`s being thrown and make them more specific (e.g. by making use of `librdkafka`s `errstr` value)
* *(Optional)* Use automatic code generation to create the different errors, as all error types are exposed by `librdkafka`'s `rd_kafka_get_err_descs()` function

**Comment by FranzBusch** [comment]
This is done and we have a `KafkaError` for this
